language: node_js
node_js:
  - "10.8.0"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    # HEROKU_API_TOKEN
    #- secure: "iiTXk0Z3YNfxda0zNS5ON2hFzrTt+ulaMe0nlucotfYUzUqhZHBktnLwhCdsQb9vOWkXEZn47wxP+n2BaNW+4/4aYUlOSp363j73my0J3TzefLrr4RC2tulEJ/xjCmT/G2mrltFlwveUuCT4AM+7rqVPzQWp+OqS6ZhskXOj4sz0s2rzzJX5kj/tU6fgPD3xwRVUSWhF76VXqhwnJK0vqfCa/IScxVbEzIBf0YtzoYfFEqHRkRc0u2ZHsqb1ZDdrUE62IRd8N9m7n6eCLpmqmMgOhlvRHaBUe5QmywMgoLuysJNECCoQfIKg1HmT2WIqTgajgdwHqhg182gMpL6cew7RqD7+WpLExlwvqY/2bBJnhsoEVAcBMoSKYeD1tAdgLmeEAIEj8eDJVu6HBDe6DAFi+wgFWVRvstk3WbvNqGP0rat4P3od+gaja8QBNpvdig525p0ekEfN7fjB7h20tpwyKGjgZr8IxaPE+bJc7v7fLq+rdCjAfkaJkzCwN44JMK7l42mgpuJ129eJLIKUrdfr2/lPn7muMMCBjHKMVlO2veJetEUhwSciWmvW3GSoGpMr9xhR7yUoDcYFgJMnHfZdBGXO5/D/JBKbb2QTsiC+lggz5nunFY1m5xXaavy0EB8fD6BMEsomnKVaKeaQjHARRBhXs99Jb8tQ2nyxy9E="
    # HEROKU_API_TOKEN
    - secure: "qeX7ZkzWhDHY3QTioNkCLhe4Qu2h9osYUcHRM/xgwY/qW2mSmyg1lNpVaCS49kzAjxvYR+rov8xp0df3Pi5jgIigCYfVQGEDQ05EP5TQJYwYcErZCRv9VY8HKptlDUKePggu3kOgjsptucnz0+Anu+redG5QTJRUwa6bH15QcOGNnIqbtnFHctwnIzV68Xsz3zxYERUgvOXKVqRztYBLJsh27o814N0qoV5hOE+w8mzX2iOU/bh1TmSHpDAtCD3JF1VJqaMjym5dyGdNcDEaJsO1DpIMvP6dVPHZDWKG6Qokxm7p4ChYtPjNUh87kVjc82/DZhoZPZ+JAZ5SDCD/Ax8goFV1yIiHDDVeg5ILYkcT2Nd//faZ3b/B9AO1KHyeNP0++vyoMH1gO10cqe2HocY+HWa5ZDpiVdaHPvPDyiBCBAsWqSUHBmqYq1YrXCGLicgwQvSj1nTmzboNVHDHDGVJqo3W6EJIdepMJmnasuQYkSV1oHpERNPbU/Sspd2CXLC0xTBnoqPkmPnCZVaQtW5YUHlFM7rsclzziZkpafia3dRruK4lM+EoFPUzbayF4E/xIQxxivXFUzgxbX8a/wgWofH3mfIEVT0LWdzA2VP6YY7F2+f/1xQrODdLJOehV37zQJZ4Vr32LvWoJ8HzEz5DSEbHsBE4link0JZT0Y4="
    # MONGODB_DATABASE
    - secure: "E3YDj4vg2LCf4ENfFN5ziVOmpKxQOja+62uiE2nwe7BlKNgP5Ju7nWoemP5c8xYmidiVSLUJWTAGkkkESAbKmlEcViOag7pqtzUb6rVcLZEpq3ZVTKUfj192+yIg98wdCIBtEagZGxRjikhiJAzMnB+JxEMzS2FqHmT7iUUYAx/YYvDr9ydAYODiolc10GB/BbXuzbC3NpBeoNFM2XPbwV9S5FU5A64a34buBh06I8td+vl7cJHGSNUA/hmkn2Z5c/qubI42IoXN54PYwXrTPrZA//adGficY1uo0HiChGr+ItL0yvsNdZAJCjoRl9Qh0GWALCVtRmIQq7xD5ncH3tk/bqxuk3e2/M4MuoEPZ2GQDe45CQep6Kxc3phHNsiO6j6HEcgzrSsA7nQC6v8NB81ErLrBu8kQoUx2W3Oe07Tj0Dsh3oBWADnruZhwhlIwUeapT2xCuly0BiBUAZKA0GQstSVr/gVBskoU0riMn8kpltSnTDL1QAtMJlmjczW5CzuYpz7LTiFBJNTmtYDPBjJAjlPphA/Yh7GHeFkuXqyLEop85TganqOPqF4yY5ht44kaQnD5EwsHbp7i/h8heB3Dn6cEgmE8bhKlSKxtZoyyTcMXZC10iusiq+j7ijnhbLtTZXeJ/IQ0fqOMy9EacMba3zbbirP/SAfjfRAFo6o="
    # DECRYPT_USER_DATA_KEY
    - secure: "xHDK7MGkqRCURzparLdg/NUxhWcj4UTme2sa/m2Ve5i9Z2Sa9qqgZC4kTXK5ja+DmB7YVBrl7mv/UZdar3BrVZU1NK+Jb2PfSFlzJ32UW1IfqPVMH/UkOJqPIWnzNx8tIuIXIEYmkyhPPU15Y1zQe3MGP+2VCXjQHrcyAiJ5DSHUgcCtpvQ4QRTxGzCgjfmQGFQr8dVuHPn+B8xS353zQflkfw9BLm/KyR6hIci1blURY7xAvFA6Vcj6mfR7A0Hnq0hMCqi7iR0w6zo81tVwu9YKYUYfiaVjlT4qtPGcAwoohbKsOLCBHLYYGWNhYfEcGOPZGq1DW3DNwSB0SqJ7gI1bpGH1qT5ItLcOjL6zyxMDGVw4bPu8wVcXXzRshoHwiNpFJDTwKydqjBCuPlRqF/5TnCiat3AEhTsuFAe5VuZlnW3NMNN2hMuFJEtcOaOIVTZ+sIqZ9yFTY0lM76SMOCQMcZIBReoNrTyRPcYcGCithaojClB2xfvHqRkl9wlwXEPkK7gQwzM3+b+jOvmpqTKMeLGlFnIJ7UgFKsvGLizZh3Mjken5xwEz1WFpMJotLQYgMilolK4ts4JxNqx1JlQCavZSs8W72pOJyr5goI4ugY4XkKzElmn5SDw+WT+O1g6nWEdRftwIJeo/tUAL905HKl5wX+P4hbWQxpJ6cQk="
    # DECRYPT_USER_DATA_IV
    - secure: "CLaMZTrZqL42qcKR5d6k7Kgugtga33IsD7SzcOTGgAllsOExZ89PCXvqVEQcbfafq1LhtoiFrNbSs44xbMzje9ORqr/FelM04VhYCfQyOz7QbwjyiVYhxeGY5FNdJPL4UATGUfHs0jSLXyjpUwoiCxXOnEmEJHxtAa9XxxsYutKEUI3d13Ni+INLOlnQ/tKoJg4IHcx9dnibdBlSQN+lSDd+mGDAPdJEN3IkcNjacyBo/zacSPGt4TrdoO+Lws7HFaICW8QcMzlFWxKK1JY7Exnfcj/ToH6qi6OKH2MxI1GmC9+io8OL0H9vge1IVNFFaUaEuNKvQy6EkPt9it71I11ulKpja2qS/vp9golaiNPrOlhbXE4YZPySyLz16Ecf62x5Lf52yVl9glUARcNdkd/typJTRh1vQC5oVM85pkvPZee/+c3nk1bYzeJhr4KzYdRRZOfhEc5V7oYpKxrP2d1fGXGG8GqAj5FnQXME3g2sGnkf2Kt5CCokN3TF3UcLpGzKQ6i8xPp7jGlqwBNuJhOSMh2xa/b1ltOTwERWVG8+DFahqEZmPpENcv6M+EsW7a6OkE7gVs+y2wkZoFcNPFFodON4DrWcOhCVYeTjMvZnjqq0iZ3nCCBmsPq5SIZ1GelyZauDhtuHOxSFGTFe5QD5mg8D+KbGnMHVCH6omzM="
    # DECRYPT_USER_DATA_SALT
    - secure: "HaX6HNt2O0cLKoRW7kyQYXgtR++bZss3PrdU+4EvKD/NdOY00S/eVPJwPFzV/fJa31DXOb8dh34ZAQ+fZ0jN2HQyBjlS3TW1Z5MGrHgekrYAcP3sz3C8lhWUkHu1uT8tn3RnYmWx5kBK31cj84lgEb1fJs+5yxHzy6o115F34b/XhtmEN7RvPyEx4zMhilZBHqGKc2XkL+AMnucmWcSOcoPgFv84hEAkmYIoqCn4xhGVj3VPL8MM8v8zW+d1BT8jRUOiVq8xXr68qmvJ6xg2KRFHyFirZuBtoXRjJa8fCad2ojhWy2uwHP3up45+W6UvySgioBZxOU8u5SS8patTVWFM66h+kaH0cHHAthbo2yOzU7izyocrT8tsveFwg7Vze6TR5sszVqos43d4isXSGjH637am9/Xws5XmhkEGBCGMP1Ei9lpsEUf2mm9aHlLEQD+3MY6PKvVpn2qCb3ECP+V/jf7Pieeah1Nk54VoaiJPL/CGXMwqLNRT594uGwKEn2djAImOXDF+MBtSOMOEP3mKmKO+Ch7tu0uqXluLbQmxCJOXCbI2eAxHvnuTDijLUTsKe3JIn2IRxqD0OEUuAfCxnGHjyYkVuy/OYdfNtgF3c+RfZIxwHT7CGia7t1zkTfDNztjHoT8DXNllvQW5cKjoMiojrSK4AS5OIx9SdNQ="
    # JWT_SECRET_KEY
    - secure: "cekRusS20KlBMqVzUoCmh8IJsxYvgTollHCp3rlUYAia+TmInN1RKofdFJkSQHI0lm3Ul06ZQ+UA3c33s1iPqmM0BcBJSSq8ohgsIQaDIhcrOEgsZLzkMriUPwaa38zaEGyl/rpMr7JyDi5Tb4mETKj0PUoR3ghR2N88hKRu8maYfk35KNAeo1yAVsaYINVguTG92kW/4+NGGyS+aE3cm12/rmAqlCj46yvdI7nbqYsQIbISidNtikRLEzYR8kV8cMwibUQ3b5qfbXvuq0xjKpoM5SFWmu7dubUubHhh5rClEIweG72JpsPLpFeYat2BNL28oDxwNMB/+eubKGXwf3QKRZP4xtP/dTRXQiAY76UGqAaYHxRw89HSzEXt01UoPWGKRRRlwxTdcvazAmhjzaTzC5oPoJbwTjvidnXl5amgeM204qsedktI1G9fEPQl9SiYO9xCS420M8W2m6UtIfjspfQ2w+SJlpsXCdbU2pDTuCdBSqy9qO6VVWZxX4fduftPpNM91UplKeVqOT7PT1NLaECZb9AhX0N9DBvqmiTjny3ZJ1nxXCldZbKJkinJJelmzyGccLIVDnvGeSIebtO/oId5zkZXyEVvOmfQNnWvaNndhZvVPnnJQE0yImw3XeZRWdpOJLclSb1DLn6Xa9376qwAv6ELq+enLbUxow4="

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - printf 'yarn-offline-mirror "./.yarn-offline-mirror"\n--production false\n--pure-lockfile true' >> .yarnrc

install:
  - yarn install

script:
  - yarn run test

before_deploy:
  - node infrastructure/herokuConfig.js

deploy:
  provider: heroku
  api_key:
    secure: S2e2ne9ze1DKQIRqG5xFnKeSps7uRY0QAo7mlG21M6plRnmZuj3GWnvCVSb0xk2VrVLanMqhiRRXYedxw767KqFX5/dW3z+LQo0omLXDMFPaTKkUjqJJtCGgf0sNFLA4iKcsJ58XATfwpJAu4y2c6xF3Jct9rldYSRE/dAZDp/zxUoLEAZnHiye2jEAwAzooYvcavdDnmUhlErnBluFlbNsqpPWTNgLPc/CI7ZXSy0txfDRqwX1R3MeICaC9RuuMtKPm/WXZhNwjPwnB8m3dWNV7c/P9HlUq/nRbe6/hGuCTM3S1misp61mbpiJ5UwePqEmecDU/ZQ6+d8KrXaMjlFWthgrIC2277D7tX09Dfwlj/94KxjFOIgv+yJf7To5fe2NTpxC675tKvXmQW4w/+IDn7qYVl9PMXWNmgG4ZzmKlZVAEmAL+uTW+GwE5GmRRsQ69tpUBXqZd6LoroZEL0K5dYTu9XXmo0lLuT72GCQ5s6ftoaWNl6KF4pmxxULzGw0Gn/Y/TqZhHP7gVxmNHufJ/RpzHg9KVPaUzs4eqwXc7dvlilF7+4oBAdUnvwEPivn2mO+FpEGnmTyghWLX+WKzY/ipaHR7Sq+UwJYDg7LqZpJ3IQxNDgHv0tCeE5rF/uOcY0gV66zvgfBqm0A+eCyw7BFQbf83lGkH5hzguJ/w=
  skip-cleanup: true
  on:
    branch: master
  app: ps-family-tree-bff
