language: node_js
node_js:
  - "10.8.0"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    # HEROKU_API_TOKEN
    - secure: "iiTXk0Z3YNfxda0zNS5ON2hFzrTt+ulaMe0nlucotfYUzUqhZHBktnLwhCdsQb9vOWkXEZn47wxP+n2BaNW+4/4aYUlOSp363j73my0J3TzefLrr4RC2tulEJ/xjCmT/G2mrltFlwveUuCT4AM+7rqVPzQWp+OqS6ZhskXOj4sz0s2rzzJX5kj/tU6fgPD3xwRVUSWhF76VXqhwnJK0vqfCa/IScxVbEzIBf0YtzoYfFEqHRkRc0u2ZHsqb1ZDdrUE62IRd8N9m7n6eCLpmqmMgOhlvRHaBUe5QmywMgoLuysJNECCoQfIKg1HmT2WIqTgajgdwHqhg182gMpL6cew7RqD7+WpLExlwvqY/2bBJnhsoEVAcBMoSKYeD1tAdgLmeEAIEj8eDJVu6HBDe6DAFi+wgFWVRvstk3WbvNqGP0rat4P3od+gaja8QBNpvdig525p0ekEfN7fjB7h20tpwyKGjgZr8IxaPE+bJc7v7fLq+rdCjAfkaJkzCwN44JMK7l42mgpuJ129eJLIKUrdfr2/lPn7muMMCBjHKMVlO2veJetEUhwSciWmvW3GSoGpMr9xhR7yUoDcYFgJMnHfZdBGXO5/D/JBKbb2QTsiC+lggz5nunFY1m5xXaavy0EB8fD6BMEsomnKVaKeaQjHARRBhXs99Jb8tQ2nyxy9E="
    # MONGODB_DATABASE
    - secure: "E3YDj4vg2LCf4ENfFN5ziVOmpKxQOja+62uiE2nwe7BlKNgP5Ju7nWoemP5c8xYmidiVSLUJWTAGkkkESAbKmlEcViOag7pqtzUb6rVcLZEpq3ZVTKUfj192+yIg98wdCIBtEagZGxRjikhiJAzMnB+JxEMzS2FqHmT7iUUYAx/YYvDr9ydAYODiolc10GB/BbXuzbC3NpBeoNFM2XPbwV9S5FU5A64a34buBh06I8td+vl7cJHGSNUA/hmkn2Z5c/qubI42IoXN54PYwXrTPrZA//adGficY1uo0HiChGr+ItL0yvsNdZAJCjoRl9Qh0GWALCVtRmIQq7xD5ncH3tk/bqxuk3e2/M4MuoEPZ2GQDe45CQep6Kxc3phHNsiO6j6HEcgzrSsA7nQC6v8NB81ErLrBu8kQoUx2W3Oe07Tj0Dsh3oBWADnruZhwhlIwUeapT2xCuly0BiBUAZKA0GQstSVr/gVBskoU0riMn8kpltSnTDL1QAtMJlmjczW5CzuYpz7LTiFBJNTmtYDPBjJAjlPphA/Yh7GHeFkuXqyLEop85TganqOPqF4yY5ht44kaQnD5EwsHbp7i/h8heB3Dn6cEgmE8bhKlSKxtZoyyTcMXZC10iusiq+j7ijnhbLtTZXeJ/IQ0fqOMy9EacMba3zbbirP/SAfjfRAFo6o="

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - printf 'yarn-offline-mirror "./.yarn-offline-mirror"\n--production false\n--pure-lockfile true' >> .yarnrc

install:
  - yarn install

script:
  - yarn run test

before_deploy:
  - node infrastructure/config.js

deploy:
  provider: heroku
  api_key:
    secure: S2e2ne9ze1DKQIRqG5xFnKeSps7uRY0QAo7mlG21M6plRnmZuj3GWnvCVSb0xk2VrVLanMqhiRRXYedxw767KqFX5/dW3z+LQo0omLXDMFPaTKkUjqJJtCGgf0sNFLA4iKcsJ58XATfwpJAu4y2c6xF3Jct9rldYSRE/dAZDp/zxUoLEAZnHiye2jEAwAzooYvcavdDnmUhlErnBluFlbNsqpPWTNgLPc/CI7ZXSy0txfDRqwX1R3MeICaC9RuuMtKPm/WXZhNwjPwnB8m3dWNV7c/P9HlUq/nRbe6/hGuCTM3S1misp61mbpiJ5UwePqEmecDU/ZQ6+d8KrXaMjlFWthgrIC2277D7tX09Dfwlj/94KxjFOIgv+yJf7To5fe2NTpxC675tKvXmQW4w/+IDn7qYVl9PMXWNmgG4ZzmKlZVAEmAL+uTW+GwE5GmRRsQ69tpUBXqZd6LoroZEL0K5dYTu9XXmo0lLuT72GCQ5s6ftoaWNl6KF4pmxxULzGw0Gn/Y/TqZhHP7gVxmNHufJ/RpzHg9KVPaUzs4eqwXc7dvlilF7+4oBAdUnvwEPivn2mO+FpEGnmTyghWLX+WKzY/ipaHR7Sq+UwJYDg7LqZpJ3IQxNDgHv0tCeE5rF/uOcY0gV66zvgfBqm0A+eCyw7BFQbf83lGkH5hzguJ/w=
  skip-cleanup: true
  on:
    branch: master
  app: ps-family-tree-bff
